// Patch notes module - dédié aux notes de mise à jour du menu principal.
// Il garde la logique UI et les données dans un fichier séparé pour faciliter
// les mises à jour sans toucher au moteur principal du jeu.

const PATCH_NOTES_HISTORY = [
  { version:'V0.3.4', notes: [
    { key:'menu.patchnotes.item73', fr:"Le raccourci \"Esports Director\" affiche maintenant le vrai logo du jeu (icône, onglet, barre des tâches) à la place de l'icône générique de navigateur" },
    { key:'menu.patchnotes.item72', fr:"Le jeu se lance maintenant toujours en plein écran, et la touche Échap ne le fait plus quitter ce mode par erreur en pleine partie (F11 reste disponible pour en sortir volontairement). Corrigé aussi de rares échecs de lancement juste après avoir ouvert le raccourci (page blanche ne répondant pas), dus à une vérification trop rapide du démarrage du serveur du jeu" },
    { key:'menu.patchnotes.item71', fr:"La touche Échap referme maintenant vraiment n'importe quelle fenêtre ouverte dans le jeu (fiche joueur, écran des sauvegardes, Forge d'Identité, filtres, négociation, popup de confirmation...), pas seulement les quelques-unes qui le géraient déjà chacune de leur côté — et referme la bonne quand plusieurs sont empilées (ex. une confirmation par-dessus une fiche déjà ouverte). Les fenêtres qui enchaînent directement sur la suite d'un match (veto, sélection d'agents, simulation en direct) restent volontairement à l'abri d'une fermeture accidentelle" },
    { key:'menu.patchnotes.item70', fr:"Nouveau système de sauvegardes multiples, accessible depuis \"Charger une Partie\" (menu principal) et le bouton \"Sauvegarder\" des Options en cours de partie : plusieurs versions d'une même carrière peuvent coexister (nommées à la main ou numérotées v02, v03...), avec en plus une sauvegarde automatique tournante en secours si le fichier courant venait à être perdu ou corrompu — sans jamais toucher à la sauvegarde en cours. L'écran liste toutes les sauvegardes (type, date en jeu, dernière sauvegarde, poids) avec création/renommage/suppression/duplication et un total d'espace utilisé, plus un bouton pour nettoyer les anciennes sauvegardes automatiques sans jamais supprimer une sauvegarde ou version créée à la main. Pas de point de restauration à la demande avant une décision risquée (mercato, match décisif...) : ça reviendrait à pouvoir annuler n'importe quel choix après coup, jugé trop facile pour un jeu de gestion. Corrigé au passage un vrai bug de fond découvert en le construisant : recharger une sauvegarde depuis son fichier disque (donc \"Continuer\"/\"Charger une Partie\" juste après avoir relancé le jeu via son raccourci) pouvait échouer silencieusement — la routine de décompression réussissait à tort sur du JSON pourtant parfaitement valide et jamais compressé, renvoyant des données illisibles à la place" },
    { key:'menu.patchnotes.item69', fr:"Simulation 3D (Valostrike) : chaque agent a maintenant sa propre identité visuelle en match — couleur de tenue, teinte d'arme et accessoires (capuche, cape, blason, épaulières, pointes d'épaule...) propres à son thème (ex. teintes ambrées pour Ignis, violet sombre pour Vexal, cristallin turquoise pour Pryzm) — jusqu'ici les 10 joueurs d'un match portaient exactement la même tenue neutre, seule la couleur d'équipe (anneau au sol, visière, brassard) les distinguait. La teinte de peau est en plus désormais tirée au hasard par personnage plutôt qu'identique pour tout le monde dans un même match" },
    { key:'menu.patchnotes.item68', fr:"Nouveau plafond salarial selon la réputation du club : proposer un salaire mensuel trop élevé par rapport au standing actuel de l'organisation (de 2 000€/mois pour un club encore inconnu jusqu'à 250 000€/mois pour les plus grandes réputations) échoue désormais automatiquement, aussi bien pour un joueur que pour un membre du staff — la fiche de recrutement affiche ce plafond en toutes lettres avant même de faire une offre" },
    { key:'menu.patchnotes.item67', fr:"Corrigé un bug de priorisation des cartes à l'entraînement (Stratégie Valostrike) : le classement automatique par niveau d'équipe, censé se retrier tout seul chaque jour (voir la note de la V0.3.3), ne se déclenchait en réalité jamais tout seul — les cartes restaient figées dans leur ordre tant qu'on ne cliquait pas manuellement sur \"actualiser\". Le classement automatique se relance maintenant réellement à chaque nouveau jour, tant qu'on n'est pas passé en tri manuel en glissant une carte soi-même" },
    { key:'menu.patchnotes.item66', fr:"Le passé du directeur (profil choisi à la création du club — Ex-joueur professionnel, Analyste data & finance, Spécialiste en communication, Directeur polyvalent — avec son bonus de réputation, budget ou supporters tout au long de la partie) a été retiré du jeu, dans la continuité de la suppression du Conseiller Exécutif : la carte du directeur, page Général, n'affiche plus que son nom et son insigne" },
    { key:'menu.patchnotes.item65', fr:"Les améliorations réalisées ce soir, ainsi que les correctifs et ajouts faits avec l'assistance de l'IA, sont désormais ajoutés automatiquement à cette note de patch pour garder un suivi clair de chaque évolution" },
    { key:'menu.patchnotes.item64', fr:"Retiré le curseur \"Taille du texte\" dans Options > Accessibilité : il donnait un rendu déformé sur certains éléments de l'interface" },
    { key:'menu.patchnotes.item63', fr:"Le bouton \"Quitter le Jeu\" du menu principal ferme enfin réellement le jeu : il se contentait jusqu'ici d'afficher un message de remerciement, et il fallait fermer la fenêtre soi-même. La partie en cours est sauvegardée une dernière fois avant de quitter" },
    { key:'menu.patchnotes.item62', fr:"Le jeu se lance maintenant depuis un vrai raccourci \"Esports Director\" avec sa propre icône : plus de fenêtre noire à laisser ouverte pendant la partie, et le jeu s'affiche dans sa propre fenêtre plutôt que dans un onglet de navigateur avec barre d'adresse. Fermer la fenêtre suffit à tout arrêter proprement. Vos sauvegardes existantes sont conservées" },
    { key:'menu.patchnotes.item61', fr:"On peut enfin se déplacer dans une piste de musique : la barre d'avancement du lecteur réagit au clic et au glissé. Elle était bien là, mais le serveur du jeu ne savait pas envoyer un morceau de fichier au milieu d'un son — le curseur revenait donc toujours en arrière. Le jeu fonctionne aussi entièrement hors ligne désormais : plus rien n'est téléchargé depuis Internet au lancement, alors qu'avant, sans connexion, les graphiques et toutes les icônes disparaissaient" },
    { key:'menu.patchnotes.item60', fr:"Le Conseiller Exécutif a été retiré du jeu (fiche sur la page Général et aperçu à la création du club)" },
  ] },
  { version:'V0.3.3', notes: [
    { key:'menu.patchnotes.item59', fr:"Corrigé un bug bloquant sur la carte Outpost (Valostrike) : deux décors beaucoup trop grands — une pyramide géante en plein milieu de la carte et une seconde posée sur le site A — coupaient en réalité le terrain en trois morceaux sans aucun passage entre eux. Résultat, les attaquants ne pouvaient pas sortir de leur zone de départ et restaient plantés là tout le round, comme si le mur de début de round ne tombait jamais, et le site A était tout simplement inatteignable. Les deux pyramides ont été ramenées à une taille qui laisse de nouveau tous les couloirs libres" },
    { key:'menu.patchnotes.item58', fr:"Corrigé un plantage au passage au jour suivant : l'annonce mensuelle du \"joueur du mois\" sur les réseaux sociaux pouvait planter pour un joueur sans rating moyen calculé" },
    { key:'menu.patchnotes.item57', fr:"Priorisation des cartes à l'entraînement (Stratégie Valostrike) : le classement se fait maintenant tout seul. Vos cartes sont retriées chaque jour du meilleur niveau d'équipe au plus faible — plus besoin de tout glisser-déposer une par une pour suivre la progression de l'effectif. Un bouton permet d'actualiser le classement immédiatement sans attendre le lendemain, et si vous préférez classer vos cartes vous-même, il suffit d'en glisser une : le classement passe en manuel et n'est plus retouché, jusqu'à ce que vous le remettiez en automatique" },
    { key:'menu.patchnotes.item56', fr:"Écran de création simplifié : les cartes de personnalisation du passé du directeur et d'aperçu du Conseiller Exécutif ont été retirées de l'écran — le profil \"Ex-joueur professionnel\" s'applique par défaut, et le Conseiller Exécutif reste généré aléatoirement comme avant, simplement sans aperçu ni régénération possible avant de lancer la partie" },
    { key:'menu.patchnotes.item55', fr:"Zenith et Outpost ont maintenant une vraie identité de décor : un relief propre au biome se dessine tout autour de la zone de jeu (collines pour Zenith, dunes pour Outpost — jamais sous vos pieds, la zone jouable reste plate), avec un vrai point de repère visible de loin (arche de grès à Outpost, arbre ancestral à Zenith) et un décor bien moins générique tout autour" },
    { key:'menu.patchnotes.item54', fr:"Corrigé un vrai bug d'affichage sur l'écran de création : sur certaines hauteurs de fenêtre, la carte \"Nom de la structure\" pouvait se comprimer et faire apparaître Pays/Couleur/Blason par-dessus les champs suivants au lieu de les afficher normalement. La carte \"Première section eSport\", elle, ne s'étire plus inutilement pour ne plus laisser un grand vide sous les jeux proposés" },
    { key:'menu.patchnotes.item53', fr:"Nouveau personnage à la création du club : votre Conseiller Exécutif, désormais prévisualisé (avec un bouton pour en générer un autre) directement sur l'écran de création, pas seulement une fois la partie lancée. Généré une fois pour toute la partie (identité, spécialités notées en étoiles, personnalité), consultable ensuite depuis une carte dédiée sur la page Général — pour l'instant une fiche à consulter, sans encore d'analyses ou d'avis automatiques pendant la partie" },
    { key:'menu.patchnotes.item52', fr:"Le passé de votre directeur ne se limite plus à un bonus unique le jour de la création : chaque profil a maintenant un vrai effet qui continue de jouer tout au long de la partie (regain de réputation, optimisation budgétaire ou croissance des supporters selon le profil, visible en jeu sur la carte Organisation et dès l'écran de création)" },
    { key:'menu.patchnotes.item51', fr:"Le terme \"manager\" pour vous désigner (vous, à la tête de l'organisation) devient \"directeur\" un peu partout (création du club, page Général) — le poste de Manager que vous recrutez, lui, sur le marché du staff, ne change pas de nom, c'est un métier différent" },
    { key:'menu.patchnotes.item50', fr:"Votre directeur a maintenant un vrai insigne personnel (médaillon doré avec vos initiales) affiché à côté de son nom dans la carte Organisation de la page Général, à la place de l'ancienne icône générique — et il apparaît déjà en aperçu, mis à jour en direct, dès l'écran de création pendant que vous tapez votre nom" },
    { key:'menu.patchnotes.item49', fr:"Le passé de votre directeur (choisi à la création) s'affiche maintenant en jeu, dans la carte Organisation de la page Général — avant, ce choix disparaissait après le premier écran" },
    { key:'menu.patchnotes.item48', fr:"Cartes de niveau de départ (création du club) : le nombre de supporters de départ s'affiche enfin sur la carte, avec la réputation et le budget déjà présents. Sans ça, \"Streamer qui se lance\" avait l'air strictement moins bon que \"Structure sponsorisée\" (moins de réputation ET moins de budget) alors que son vrai atout — une communauté énorme dès le départ — restait invisible" },
    { key:'menu.patchnotes.item47', fr:"Nouveau à la création du club : le passé de votre directeur (Ex-joueur professionnel, Analyste data & finance, Spécialiste en communication, Directeur polyvalent) donne un vrai bonus de départ — réputation, budget ou supporters selon le profil choisi, en plus du scénario de départ" },
    { key:'menu.patchnotes.item46', fr:"Écran de choix du slot Challenger de départ (Valostrike) : chaque équipe a maintenant un médaillon avec son initiale plutôt qu'un simple bloc de texte, coins plus généreux et relief — moins plat que les rectangles bruts d'avant" },
    { key:'menu.patchnotes.item45', fr:"Retiré le choix d'icône du profil directeur (à la création du club) : la grille de petites icônes génériques n'apportait rien de bien lisible, seul le nom reste personnalisable" },
    { key:'menu.patchnotes.item44', fr:"Nouveau : pays de la structure à choisir à la création du club, et notoriété des sponsors (Locale/Nationale/Internationale, visible en badge sur chaque offre) — les sponsors les plus prestigieux paient bien plus mais n'approchent qu'un club déjà réputé. Des sponsors de paris sportifs peuvent désormais approcher le club : très généreux partout, mais risqués (perte de supporters, de réputation, polémique sur les réseaux) dans les pays où ce type de publicité est mal vue ou interdite" },
    { key:'menu.patchnotes.item43', fr:"Bassin de sponsors potentiels triplé (48 → 192 marques fictives) pour éviter les répétitions d'offres sur les longues carrières" },
    { key:'menu.patchnotes.item42', fr:"Concepteur de produit Merch entièrement réorganisé pour tenir sur un seul écran, sans défilement : aperçu et catégorie à gauche, tous les réglages (nom, couleur, matière, technique, prix, quantité) à droite. Catalogue recentré sur le gear esport — Clavier, Souris et Chaise gaming rejoignent Maillot, Casquette, Mug, Sac, Porte-clés et Gourde avec de vrais visuels produit recolorables, tandis que Veste, Kit Pro, Mascotte peluche, Chaussettes, Lunettes et Poster ont été retirés du catalogue" },
    { key:'menu.patchnotes.item41', fr:"Visuels produit Merch nettement plus soignés : chaque silhouette (maillot, casquette, mug, sac, veste, gourde...) gagne de vrais détails de finition (col, coutures, anse, liseré, boutons) et un rendu en volume — reflet brillant, ombrage et ombre portée — plutôt qu'un aplat de couleur plat. Rendu 100% généré (pas de vraie IA d'image : ça demanderait une clé API payante et visible par tous, incompatible avec un jeu local sans serveur), mais un résultat bien plus proche d'un vrai mockup produit. Corrigé au passage un défaut d'affichage sur la veste (une tache grise près du col) et remis le fond de carte en dégradé aux couleurs du club (à la place du fond uni + halo)" },
    { key:'menu.patchnotes.item40', fr:"Concepteur de produit Merch : personnalisation visuelle complète du produit — couleur principale au choix, option dégradé (deux couleurs) à la place d'une couleur unie, motif appliqué directement sur le produit (rayures ou pois, avec ses propres couleurs), et surtout un vrai import d'image personnelle (PNG/JPG/WEBP) qui remplace la silhouette générée sur le visuel du produit, entièrement en local dans la sauvegarde. Le fond derrière le produit, lui, reprend désormais toujours les couleurs du blason du club, pour que chaque produit reste visuellement rattaché à l'organisation" },
    { key:'menu.patchnotes.item39', fr:"Boutique Merch rapprochée d'un vrai éditeur de produits dérivés, sans fausse promesse de photo (aucun hébergement d'image possible dans ce jeu, donc pas de vrai mockup ni d'upload de logo). Chaque produit a maintenant une vraie silhouette (maillot, casquette, mug, sac, gourde, lunettes...) en couleur du club, plutôt qu'une icône plate dans un carré dégradé. Un champ « texte / slogan » optionnel s'affiche directement sur le visuel du produit. Et une nouvelle Technique d'impression (Numérique/Sérigraphie/Broderie) vient s'ajouter à la matière et la catégorie comme 3e levier économique — la sérigraphie coûte cher à préparer mais revient très peu cher à l'unité ensuite, l'inverse du numérique" },
    { key:'menu.patchnotes.item38', fr:"Concepteur de produit Merch : l'icône de la Casquette (un chapeau de cowboy vu de côté, illisible en petit) est remplacée par une icône de toque, nettement plus reconnaissable comme couvre-chef ; l'icône de la Mascotte peluche (une simple empreinte de patte, ambiguë) devient un dragon. Le nom de la catégorie sélectionnée s'affiche aussi en toutes lettres à côté du titre \"Catégorie\" plutôt que de compter uniquement sur l'icône" },
    { key:'menu.patchnotes.item37', fr:"Concepteur de produit Merch : le curseur de matière changeait visuellement de longueur selon le libellé affiché à côté (« Coton standard » vs « Textile technique », de tailles différentes) — l'étiquette a maintenant une largeur fixe, le curseur ne bouge plus. Retiré au passage le choix de couleur par produit (primaire/accent) : chaque produit reprend directement les couleurs du blason du club, comme au tout début" },
    { key:'menu.patchnotes.item36', fr:"Fiche produit Merch : le type de produit (Maillot, Casquette, Mug...) s'affiche enfin en texte sur la carte à côté de la matière — jusqu'ici seule la petite icône l'indiquait, impossible à deviner à coup sûr. Nouvelle catégorie ajoutée au passage : Lunettes" },
    { key:'menu.patchnotes.item35', fr:"Fiche produit Merch clarifiée : le bilan du mois écoulé affiche maintenant Commandé/Vendu/Invendu côte à côte au lieu du seul nombre vendu, et le champ de production porte désormais une étiquette \"Prochaine production\" pour ne plus le confondre avec ce bilan passé" },
    { key:'menu.patchnotes.item34', fr:"Concepteur de produit Merch : prix de vente et quantité à produire ne sont plus pré-remplis avec une suggestion — ils démarrent à 0 et le restent tant que vous ne les saisissez pas vous-même, plutôt que de deviner un chiffre à votre place. Le bouton \"Lancer ce produit\" reste désactivé tant que ces deux champs n'ont pas de vraie valeur (prix au-dessus du coût de fabrication, quantité supérieure à 0)" },
    { key:'menu.patchnotes.item33', fr:"3 ajustements sur le concepteur de produit Merch, suite à des retours directs. La quantité à produire au lancement ne bouge plus toute seule quand on déplace le curseur de matière (seule sa note de coût se met à jour avec le nouveau coût unitaire) — jusqu'ici elle se recalculait automatiquement à chaque glissement, gênant à l'usage. L'étiquette de matière (ex. « Textile technique ») est repositionnée juste à côté du curseur au lieu d'être plaquée à l'autre bout de l'écran. Et surtout, coût de fabrication et demande dépendent enfin de la CATÉGORIE du produit, pas seulement de sa matière : un mug ou un porte-clés coûtent nettement moins cher à produire qu'une veste au même niveau de matière, et se vendent en bien plus gros volume (achat d'impulsion) — jusqu'ici un mug \"Textile technique\" coûtait exactement comme un maillot \"Textile technique\", ce qui n'avait aucun sens" },
    { key:'menu.patchnotes.item32', fr:"Concepteur de produit Merch approfondi, sur deux retours successifs. D'abord retiré le système de gammes à cases cliquables (Basique/Premium/Collector, puis une version à 5 « matières » en cartes — toujours jugée trop proche d'un choix de pack tout fait) : un seul curseur continu de qualité de matière (Coton standard → Matériaux nobles) fait maintenant évoluer en douceur coût de fabrication, frais de lancement et sensibilité de la demande, sans aucune case à cocher. Ensuite ajouté un vrai contrôle économique par produit : prix de vente librement fixé (au lieu d'un prix imposé), quantité à produire dès le lancement (au lieu d'attendre le mois suivant pour la régler), avec le coût de fabrication à l'unité et les frais de lancement affichés en direct pendant qu'on ajuste. Corrigé au passage : le bouton \"Lancer ce produit\" restait grisé après avoir tapé un nom, tant qu'aucun autre champ n'était retouché ensuite" },
    { key:'menu.patchnotes.item31', fr:"Boutique Merch retravaillée : chaque produit a maintenant sa propre couleur (primaire + accent), choisie dans le concepteur plutôt qu'imposée par le blason du club ; bannière animée en tête de boutique aux couleurs du club (toujours pas de vraie photo, mais un fond vivant plutôt qu'un bloc plat) ; bandeau des sponsors sous contrat affiché au-dessus du catalogue (en texte, faute de vrais logos de marque importés) ; les statistiques financières (profit, historique mensuel) ont été retirées de l'onglet Merch et rejoignent Finances, où elles se recoupent avec les autres revenus du club" },
    { key:'menu.patchnotes.item30', fr:"Nouvel onglet Finances > Merch : concevez votre propre catalogue de produits dérivés (maillot, veste, casquette, mug, sac, porte-clés, poster, mascotte peluche, chaussettes, gourde), chacun dans une gamme Basique/Premium/Collector avec son propre coût de lancement, sa marge et sa demande — la demande dépend de vos supporters et de votre réputation, avec une sensibilité très différente par gamme (le Collector ne se vend quasiment qu'aux grandes organisations réputées, le Basique se vend dès une petite base de fans). Chaque mois, vous fixez vous-même le volume à produire par produit avant que la demande réelle ne soit connue : produire trop peu laisse des ventes sur la table, trop laisse du stock invendu payé pour rien" },
  ] },
  { version:'V0.3.2', notes: [
    { key:'menu.patchnotes.item29', fr:"Correction d'un vrai bug de blason (suite) : ouvrir la Forge d'Identité depuis le crayon \"Modifier le blason\" de la fiche de structure (Club > profil) l'affichait bien techniquement, mais complètement invisible ET inerte, cachée SOUS la fiche encore ouverte au-dessus (un souci de calque déjà rencontré et corrigé une fois pour la fiche joueur, pas encore pour la Forge) — impossible de valider un nouveau blason par ce chemin, ce qui explique que le blason personnalisé n'apparaissait jamais en jeu. La Forge s'affiche maintenant bien au premier plan, utilisable normalement" },
    { key:'menu.patchnotes.item28', fr:"Correction d'un vrai bug de blason : votre organisation affichait le bon blason personnalisé (Forge d'Identité) dans la barre latérale et le tableau de bord, mais un blason générique généré au hasard à partir de son nom dans TOUS les classements/brackets (RLCS, Kickoff, Ranked, World Hub, Ascension...) — la fonction partagée par ces tableaux ne savait pas reconnaître votre propre ligne. Elle utilise maintenant le vrai blason personnalisé partout où votre organisation apparaît" },
    { key:'menu.patchnotes.item27', fr:"5 nouvelles pistes hip-hop/soul instrumentales ajoutées à la playlist du menu (Energetic Lo-Fi Hip-Hop, Smooth Lo-Fi Hip Hop, Lo-Fi Fashion Chill Hip Hop, Breakfast In Paris, Powerful Trap Beat), en plus des lofi déjà présentes" },
    { key:'menu.patchnotes.item26', fr:"Refonte du pop-up de simulation en direct Rocket Champ : les deux équipes affichent maintenant leur blason (au lieu d'un panneau texte nu), et un nouveau mode « Vue de terrain » propose un mini-terrain animé vu du dessus (ballon et voitures qui dérivent, but qui s'illumine et bannière au moment du score, fil de buts compact en dessous) — choix disponible juste avant chaque match, à côté du mode texte (désormais lui aussi habillé : blasons, entrées de buts avec icône et animation d'apparition)" },
    { key:'menu.patchnotes.item25', fr:"Icône Call of Duty changée : elle réutilisait la même mire de visée (crosshair) que Valostrike, ne le distinguant pas visuellement des autres jeux ; remplacée par une icône d'arme propre à Call of Duty" },
    { key:'menu.patchnotes.item24', fr:"Forge d'identité : l'anneau/liseré des accents « ring » et « double » suivait la boîte rectangulaire de l'aperçu et se faisait couper n'importe comment sur les formes à pointes (Écusson, Hexagone, Sceau...) — visible aux angles où l'accent débordait ou disparaissait au lieu de longer le contour. L'anneau est maintenant construit en épousant exactement le même contour que la forme choisie, quelle que soit sa taille d'affichage (aperçu de la Forge, barre latérale, blasons d'équipes adverses)" },
    { key:'menu.patchnotes.item23', fr:"Deux bugs de recrutement corrigés pour Rocket Champ (et plus largement tout jeu hors Valostrike) : le bouton \"Faire une offre\" affiché sur la fiche d'un agent libre échouait toujours avec \"Ce joueur n'est pas transférable pour le moment\" au lieu d'ouvrir la négociation, et affichait en prime un prix de transfert au lieu d'un salaire mensuel comme il se doit pour un agent libre. Par ailleurs, chaque équipe Rocket Champ se voyait polluer ses statistiques de terrain avec les 7 noms de cartes Valostrike (Quai IX, Vertex...), jamais joués, au lieu de ses vraies arènes (Neo Tokyo, DFH Stadium...) — sans impact sur la simulation des matchs, mais des données trompeuses" },
    { key:'menu.patchnotes.item22', fr:"Le jeu s'appelle désormais Esports Director (anciennement eSports Manager) — menu principal, titre de la fenêtre, options et fenêtre du serveur local mis à jour. Écran de création : le blason affiché avant toute personnalisation était tiré au hasard à partir du nom de la structure et pouvait tomber sur des combinaisons forme/icône peu flatteuses (ex. hexagone + montagne) ; il s'agit maintenant d'un blason classique fixe (écu + couronne + liseré), qui ne varie plus qu'avec la couleur choisie" },
    { key:'menu.patchnotes.item21', fr:"Forge d'identité : correction du positionnement de l'emblème sur la forme Blason — centré sur tout le carré englobant, il débordait dans la pointe basse (rogné par le contour) tout en laissant un vide au-dessus, rendant l'ensemble bancal (« les formes et accents se placent mal »). L'emblème est maintenant recentré sur la partie utile (rectangulaire) du blason, quelle que soit sa taille d'affichage (aperçu de la Forge, barre latérale, blasons d'équipes adverses). Les autres formes (hexagone, cercle, losange, carré, octogone, goutte), déjà symétriques, sont inchangées" },
    { key:'menu.patchnotes.item20', fr:"Nouvelle carte jouable : Quai IX. Port commercial nocturne avec un vrai moteur 3D (comme Zenith et Outpost). Trois passes de correction suite à des retours directs. D'abord un vrai réseau de couloirs (milieu connecté, 3 sorties de spawn attaque, 2 approches par site en plus du flanc). Puis un milieu resserré en couloirs étroits (2-3 cases au lieu de 6-13) et le site B rapproché du spawn défense par une liaison directe. Enfin, sur un dernier retour (« couloirs trop directs, ajoute des objets cohérents ») : tous les axes sont désormais en zigzag (chaque couloir tourne au moins deux fois au lieu d'aller en ligne droite), et le décor est nettement plus dense — lampadaires le long de chaque tronçon, caisses/tonneaux/palettes/sacs de sable en alternance sur les bords, panneaux directionnels aux carrefours, véhicule et blocs de béton en plus sur le site A. Ajoutée au pool de cartes compétitif (rejoint d'abord le hors-rotation, éligible à la rotation active au prochain patch majeur)" },
    { key:'menu.patchnotes.item19', fr:"Map Editor : les biomes se ressemblaient encore trop entre eux au-delà de la densité — l'aperçu de l'éditeur ne piochait que dans 8 props génériques (troncs, fougères, champignons, buissons) recyclés à l'identique pour tous les biomes, et Désert/Ville futuriste n'avaient carrément AUCUN prop de détail (contrairement à ce que la partie jouée affichait déjà réellement, avec cactus/dunes en désert par exemple). Chaque biome pioche maintenant dans son propre lot d'éléments caractéristiques dans l'éditeur aussi : cactus et dunes en désert, mangroves/roseaux/algues en marécage, baobabs en savane, cristaux en ville futuriste, tournesols/fleurs en prairie, pics rocheux en montagne, etc. — l'aperçu de l'éditeur correspond enfin à ce qui s'affiche vraiment une fois la carte jouée" },
    { key:'menu.patchnotes.item18', fr:"Map Editor : correction de deux problèmes qui rendaient TOUS les biomes trop vides, pas seulement Toundra/Ville. D'abord la vraie cause : l'anneau de décor s'étendait bien plus loin (jusqu'à 480m) que ce que le brouillard laisse voir (déjà quasi invisible au-delà de 250-300m), donc une bonne partie des éléments générés était en réalité gaspillée hors de vue — l'anneau est resserré à 300m et le nombre de bandes augmenté, ce qui concentre le même décor dans la zone réellement visible (environ 3 fois plus dense à l'œil). Ensuite un vrai bug de forme trouvé sur les arbres à feuillage large (tropical, prairie...) : leur couronne était étirée 70% plus haute que large, ce qui la faisait ressembler à un sapin pointu au lieu d'un feuillu rond même si le bon modèle était utilisé — proportions corrigées pour une couronne large et arrondie" },
    { key:'menu.patchnotes.item17', fr:"Map Editor : le biome Toundra était de très loin le plus vide de tous les biomes — 50% du terrain restait nu contre 80-98% couverts pour les autres, et sans le moindre élément de glace/neige malgré le thème (juste des rochers/buissons génériques teintés en pâle). Densité remontée à 85%, avec deux nouveaux éléments propres au thème (blocs de glace, plaques de neige). Le biome Ville futuriste, également nettement plus vide que les autres (48%), gagne un peu de gravats/blocs de béton en plus des tours déjà présentes" },
    { key:'menu.patchnotes.item16', fr:"Map Editor : le biome choisi pour une carte (Désert, Toundra, Forêt tropicale...) est enfin visible une fois la carte jouée — jusqu'ici, ce choix ne servait qu'à l'aperçu de l'éditeur et disparaissait totalement à l'export, le sol restant toujours le même vert générique en jeu quel que soit le biome sélectionné. Le sol constructible de l'éditeur (les cases sans tuile posée dessus, jusque-là toujours grises) prend maintenant la teinte du biome choisi, et la carte jouée reprend cette même couleur de sol sur toute son étendue, avec en plus un peu de décor cohérent (cactus en désert, sapins en taïga, glace en toundra...) parsemé autour de la zone de jeu pour qu'elle ne paraisse plus vide" },
    { key:'menu.patchnotes.item15', fr:"Simulation 3D (Valostrike) : Time-Out tactique — dernière étape, la visualisation 3D du plan. Pendant le Time-Out, choisir un round de l'arbre affiche directement sur la carte les trajectoires calculées par le même pathfinding qui déplace réellement les agents (donc en suivant les vrais murs/couloirs, jamais une ligne arbitraire), avec une flèche animée par flanc (couleur différente pour un Split ou un Fake), un point lumineux qui parcourt le trajet pour matérialiser le timing, et des icônes d'utilitaire (fumée/flash/etc.) dérivées du vrai kit de l'équipe autour du site visé. Tout disparaît automatiquement à la fin du Time-Out. Le système de Time-Out est maintenant complet sur les 4 étapes prévues" },
    { key:'menu.patchnotes.item14', fr:"Simulation 3D (Valostrike) : Time-Out tactique — ajout de l'Assistant Coach (3e étape). Un bouton dédié laisse l'IA recommander automatiquement une consigne à la place de la saisie manuelle, avec un % de confiance, un niveau de risque et 2-3 raisons concrètes (historique réel de réussite par stratégie, écart d'économie entre les deux équipes, site où la défense adverse a été la plus perméable récemment, série de défaites en cours) — aucune donnée inventée, uniquement des signaux déjà suivis par le vrai moteur de jeu" },
    { key:'menu.patchnotes.item13', fr:"Simulation 3D (Valostrike) : le Time-Out tactique (2e étape) permet maintenant de taper une consigne pendant la pause (Fast B, Split A, Eco, Force Buy, Mid Control, Retake Setup...) — plus de 25 mots-clés reconnus. Un arbre de décision sur 3 rounds se génère automatiquement, avec une branche Victoire et une branche Défaite à chaque round, jusqu'à 4 scénarios possibles au round 3. Chaque round de l'arbre propose une stratégie, un objectif, un achat recommandé et les utilitaires disponibles dans le vrai roster — l'économie projetée round par round utilise les mêmes formules que le vrai jeu (prime de victoire/défaite), donc l'arbre ne recommande jamais un achat que l'équipe ne pourrait pas réellement se payer. Quand c'est l'IA adverse qui appelle le Time-Out, elle génère aussi son propre plan (affiché en lecture seule)" },
    { key:'menu.patchnotes.item12', fr:"Simulation 3D (Valostrike) : ajout du Time-Out tactique façon compétitif pro (1re étape). Chaque équipe dispose d'1 Time-Out par side (jamais récupéré une fois pris) + 1 unique pour toute l'overtime. Bouton dédié pour le déclencher (toujours à la coupure entre deux rounds, jamais en plein combat) ; l'IA adverse peut aussi en demander un elle-même après une série de défaites. Popup d'annonce avec équipe/score/side/compte à rebours réel de 30s, pulsation lumineuse colorée au spawn de l'équipe dans la vue 3D, carte dédiée dans le fil d'événements, compteur permanent sous le bandeau de score (bascule automatiquement en compteur d'overtime à partir du round 25), et historique consultable de tous les Time-Outs du match. Le contenu tactique (consignes, plan sur 3 rounds, recommandations IA, visualisation 3D du plan) arrive dans une prochaine mise à jour" },
    { key:'menu.patchnotes.item11', fr:"Simulation 3D (Valostrike) : la barrière de spawn (murs bleus, 10s en début de round) figeait totalement les deux équipes — elles peuvent désormais se déplacer normalement pour se mettre en place, juste sans pouvoir dépasser le mur avant qu'il ne tombe, comme en vrai. Correction au passage d'un bug plus profond découvert en la construisant : la position d'un agent en déplacement suit un compteur de progression interne qui continuait d'avancer même quand l'agent était visuellement bloqué au mur — sans le correctif, tout le monde aurait littéralement téléporté à sa position réelle (10s de marche non bridée) dès la chute de la barrière" },
    { key:'menu.patchnotes.item10', fr:"Simulation 3D (Valostrike) : ajout de la barrière de spawn, comme en vrai — au début de chaque round, un mur bleu translucide immobilise chaque équipe 10 secondes à son point de spawn avant que qui que ce soit ne puisse bouger. Jusqu'ici les défenseurs partaient prendre leurs positions/angles instantanément dès le spawn, avant même le vrai début du round (signalé par un joueur). Mode réalisateur : corrigé le temps d'activation trop long — la caméra restait totalement figée tant qu'aucun duel n'était en cours (ex. juste après activation, ou pendant la barrière de spawn) ; elle affiche maintenant tout de suite un plan d'ensemble et bascule sur le premier duel dès qu'il démarre" },
    { key:'menu.patchnotes.item9', fr:"Simulation de carte sans moteur 3D (Valostrike) : le fil du round affiche désormais une phrase de situation quand la manche se termine sur un clutch (ex. « Clutch 1v2 pour la défense — manche remportée en désamorçant malgré le désavantage numérique »), calculée à partir des vrais kills du round plutôt qu'un simple badge « 1v2 » sans suite logique. Corrigé au passage : les buy-types (Force/Semi/Full/Hyper Buy) pouvaient être choisis même sans avoir de quoi les payer réellement (ex. Force Buy dès 4000 NX pour un achat qui coûte 4200), ce qui vidait le compte au round suivant et rendait deux économies très proches (4100 vs 4200 NX) visiblement incohérentes ; Save coûtait 500 NX au lieu de 0 (économiser ne devrait jamais rien coûter)" },
    { key:'menu.patchnotes.item0z', fr:"Correction d'un vrai bug d'économie NX en simulation 3D (Valostrike) : le changement de côté à la mi-match (round 13) ne remettait jamais les crédits à zéro ni ne retirait les armes déjà achetées — l'équipe qui avait dominé la 1re mi-temps abordait donc la 2e avec son stock de crédits ET son arme encore en poche, ce qui supprimait purement et simplement le round pistolet de la 2e mi-temps et déséquilibrait toute la suite du match. Les deux équipes repartent maintenant à 800 NX et au pistolet de base au round 13, comme au vrai round 1" },
    { key:'menu.patchnotes.item0y', fr:"Optimisation FPS de la simulation 3D (Valostrike) : la carte Zenith s'est révélée composée de plus de 13 000 mailles rien que pour son sol (dallage détaillé en centaines de petites tuiles), dont près de 7000 recalculaient inutilement leur ombre portée à chaque frame — un carrelage posé à plat n'a jamais d'ombre visible à projeter. Ces tuiles de sol, ainsi que les plus petits détails procéduraux (boulons, coutures...) trop fins pour qu'une ombre s'y voie, ne projettent plus d'ombre du tout ; qualité d'ombre légèrement allégée (toujours nette, juste moins coûteuse à recalculer en continu) ; calcul de ligne de vue de l'IA (déjà appelé plusieurs dizaines de fois par frame en plein duel) allégé pour ne plus réallouer de mémoire à chaque appel" },
    { key:'menu.patchnotes.item0x', fr:"Correction d'un bug empêchant la vue subjective de fonctionner en jeu réel : les cartes de joueurs du HUD (Zenith et Outpost) étaient en réalité inertes au clic — la souris traversait la carte et cliquait la scène 3D en dessous — alors que mes propres tests précédents, faits par appel de code plutôt qu'un vrai clic souris, ne l'avaient pas révélé. Cliquer un joueur dans le HUD bascule maintenant bien la caméra en vue subjective" },
    { key:'menu.patchnotes.item0w', fr:"Simulation 3D (Valostrike) : nouvelle vue subjective. Cliquer un joueur dans le HUD bascule la caméra à hauteur de ses yeux, orientée dans sa direction de visée réelle, au lieu de rester sur la vue spectateur libre — un second clic sur le même joueur (ou Échap) quitte le mode. Si le joueur suivi meurt, la caméra bascule automatiquement sur son allié vivant le plus proche au lieu de rester braquée sur un corps immobile ; s'il ne reste plus aucun allié vivant, retour à la vue libre. Toute manipulation manuelle de la caméra (glisser/molette) quitte aussi le mode subjectif" },
    { key:'menu.patchnotes.item0v', fr:"Simulation 3D (Valostrike) : le tag d'équipe s'affiche enfin devant le pseudo au-dessus des personnages (ex. « JL Kreta » pour l'organisation JL) — la donnée existait déjà côté manager mais n'était jamais lue par l'étiquette flottante en jeu. Look opérateur tactique repris de la tête aux pieds (référence type CS), corps compris cette fois : torse/bras/gilet/pochettes/sac à dos/jambes passent en tons ternes gris-olive-tan au lieu du rouge/vert vif sur toute la tenue — la couleur d'équipe reste lisible via l'anneau au sol, la visière et un nouveau petit brassard sur le bras plutôt que de teindre tout le corps. Tête entièrement cagoulée (plus de peau/cheveux visibles) avec visière/lunettes de protection, mains repositionnées pour tenir réellement l'arme" },
    { key:'menu.patchnotes.item0u', fr:"Simulation 3D (Valostrike) : personnages retravaillés, plus détaillés et plus crédibles anatomiquement. Cou ajouté entre tête et torse (avant : sphère posée à cru sur un cylindre), mains, bottes, ceinture + pochettes tactiques, sac à dos, mâchoire, tête légèrement aplatie plutôt qu'une sphère parfaite. Correction du pivot des jambes : la marche faisait tourner toute la jambe sur son propre centre au lieu de l'articuler depuis la hanche — les bottes suivent maintenant naturellement le mouvement. Arme reconstruite en plusieurs pièces (corps/chargeur/crosse/poignée avant/canon selon le palier d'achat réel) au lieu d'une seule boîte plate. Environ 24 éléments par personnage contre 13 avant, dans les deux fichiers de simulation (Zenith et Outpost)" },
    { key:'menu.patchnotes.item0t', fr:"Map Editor : refonte du réalisme des arbres, moteur commun à toute la famille Arbres. Tous les troncs (sauf Bambou/Baobab, traités à part) ont désormais un évasement des racines au pied — un tronc parfaitement cylindrique du sol au sommet était le signal \"forme géométrique\" le plus flagrant. Chaque arbre a en plus un léger dévers naturel, plus aucun n'est parfaitement vertical. Sapin/Pin : 4 étages de branches dégressifs et texturés différemment au lieu de 2 gros cônes identiques. Saule pleureur : frondaison éclatée en plusieurs touffes + 16 lianes tombantes (contre 10, toutes identiques avant). Baobab : tronc massif et renflé qui lui est propre, plus le même tronc fin générique que tous les autres arbres — c'est justement ce tronc démesuré qui définit un baobab. Palmier : palmes en 2 segments qui s'affaissent sous leur poids au lieu d'une planche bien droite, plus des noix de coco" },
    { key:'menu.patchnotes.item0s', fr:"Map Editor : audit complet de fin de passe détail. Cactus (épines + fleurs) et tas de neige (éclats de glace) enrichis. Le reste de la bibliothèque a été vérifié un par un : les grosses structures (Bâtiment, Tour, Entrepôt, Usine, Bureau...) étaient déjà très détaillées (jusqu'à 220 éléments), et les petits props/éléments d'eau restants (drapeau, pot de fleurs, nénuphar, mare...) sont déjà au bon niveau pour ce qu'ils représentent — pas de sur-détail ajouté juste pour ajouter" },
    { key:'menu.patchnotes.item0r', fr:"Map Editor : encore une salve de détail — décors, props et éléments de verticalité cette fois. Bloc de béton, tonneau (cerclages + couvercle), caisse (cornières), roue cassée (moyeu + rayons), tapis (bordure + médaillon central) : tous n'étaient qu'une seule forme nue. Rampe verticale et rampe d'accès : bandes antidérapantes + garde-corps, comme la rampe de parking. Ascenseur : jusque-là une simple dalle plate, gagne montants, garde-corps et boîtier de commande" },
    { key:'menu.patchnotes.item0q', fr:"Map Editor : suite de la passe détail, sur Nature et Structures cette fois. Les arbres à frondaison ronde (Chêne, Bouleau, Cerisier, Érable — jusque-là un seul cône lisse, tous identiques) ont maintenant une silhouette de feuillage cassée en plusieurs touffes de teintes légèrement différentes au lieu d'une boule parfaite. Les maisons (les 9 de la famille « Maisons régionales », dont Bois/Pierre/Chalet/Hutte/Cabane...) n'étaient que 3 boîtes (murs/toit/porte) — elles ont désormais fenêtres, cheminée et marche d'entrée. Tronc tombé, rocher isolé et grand rocher enrichis (mousse, galets épars, anneau de coupe). Rampe, Pyramide et Tente — jusqu'ici une seule forme géométrique nue chacune — ont gagné bandes antidérapantes et garde-corps, pierre de faîte et entrée basse, et rabat d'entrée avec haubans/piquets" },
    { key:'menu.patchnotes.item0p', fr:"Map Editor : correction d'un vrai bug de géométrie touchant près de 30 assets (bambou, murs modulaires — dont toutes les pièces d'angle —, plusieurs murs à thème, les 4 nouveaux éléments de couverture, station-service, silo, fort, mine, serre, abri bus, herbe haute, roseau, liane, mangrove...) : de nombreux objets étaient posés à moitié enterrés dans le sol à cause d'un mauvais calcul de hauteur, ce qui les faisait paraître chétifs, tordus ou juste \"moches\" une fois en carte. Le bambou en particulier était méconnaissable : cannes filiformes à moitié invisibles sous terre. Cannes de bambou repensées : bien plus épaisses, noeuds annelés (le vrai trait distinctif du bambou, absent avant), léger dévers naturel par canne, feuillage en touffes plutôt qu'un seul cône plein. Nouveau système de détail réutilisable (éclats, fissures, coulures/taches, boulons) appliqué aux murs les plus nus (Brique, Bois, Marbre, Granit, Rouillé, Temple) ; le mur Obsidienne, jusque-là totalement vide, reçoit désormais des veines cristallines lumineuses et des éclats de verre volcanique en relief" },
    { key:'menu.patchnotes.item0o', fr:"Map Editor : passe rangement/réalisme + habillage aligné sur le jeu. Palette d'assets réorganisée : les 3 grosses catégories (Murs 65, Nature 66, Structures 67) sont maintenant regroupées par familles thématiques (Modulaire, Historique, Industriel, Arbres, Points d'eau...) au lieu d'une seule grille plate de 60-70 tuiles à faire défiler. Recherche d'assets corrigée : chercher une variante modulaire (ex. « porte ») retrouve désormais toutes les portes, sous-catégorie automatiquement dépliée. Nouveau panneau « Objets de la carte » (toujours visible dans l'inspecteur) qui liste tous les objets placés groupés par catégorie, cliquables pour sélectionner (Maj/Ctrl+clic pour ajouter/retirer), surlignage synchronisé dans les deux sens avec le viewport. Libellés dupliqués de la nature différenciés (Buisson dense/clairsemé, Fougère haute/basse, Arbre mort noueux/décharné). L'éditeur reprend maintenant les couleurs et la typographie du jeu (charbon + doré, polices Manrope/Fraunces) au lieu de son ancien thème bleu/cyan. Toutes les textures procédurales (pierre, brique, béton, bois, sol...) passent de 256×256 à 512×512, plus fines de près. Légère variation de teinte par exemplaire posé sur les murs/décors sans détail de surface dédié, pour casser l'effet couleur plate identique partout" },
    { key:'menu.patchnotes.item0n', fr:"Map Editor amélioré : bouton « Tester en match » qui ouvre directement votre carte en cours dans un vrai match 3D (plus besoin de copier-coller le JSON à la main), bouton « Vérifier pour Valostrike » qui contrôle la présence des sites/spawns et d'assez de sol avant de jouer. Édition multi-sélection enfin fonctionnelle (déplacer/tourner/redimensionner plusieurs objets à la fois les décalait tous sur le premier objet sélectionné). Grille au sol visible selon le pas d'accrochage choisi, retour visuel sur annuler/rétablir, compteur d'objets par catégorie, lumière de remplissage qui adoucit les ombres dures. 13 nouveaux décors (couvertures, verticalité, éléments tactiques)" },
    { key:'menu.patchnotes.item0m', fr:"Cartes 3D et personnages Valostrike : la bibliothèque de décors du Map Editor (284 assets, murs/structures/nature très détaillés) est désormais PARTAGÉE avec le moteur de match 3D — Zenith et Outpost gagnent d'un coup tout ce niveau de détail (fini les murs/props réduits à de simples boîtes grises), et toute nouvelle carte construite dans l'éditeur s'affichera pareil en vrai match. Côté personnages : jambes qui animent en marchant, recul visible à chaque tir, mort qui bascule et s'estompe au lieu de disparaître instantanément, barre de vie et pastille d'armure flottantes au-dessus de chaque agent, silhouette d'arme qui suit le vrai palier d'achat, accent de couleur par rôle (Duelliste/Initiateur/Contrôleur/Sentinelle/Flex)" },
    { key:'menu.patchnotes.item0l', fr:"Nouveaux leviers stratégiques Valostrike, propres au FPS tactique : doctrine économique (force-buy vs save discipliné, agit vraiment sur les achats NX), agressivité d'entrée de site (rush vs exécutions travaillées, agit vraiment sur les choix de round de l'IA), discipline de rotation/retake — les 3 avec un effet réel en match, pas une force brute générique. La synergie de composition d'agents (déjà affichée sur la tier list) compte enfin dans la vraie force d'équipe, pour vous comme pour vos adversaires. Un bouton dédié laisse le Head Coach gérer ces doctrines à votre place" },
    { key:'menu.patchnotes.item0k', fr:"Refonte complète de la stratégie Rocket Champ : le style unique emprunté à Valostrike est remplacé par 3 axes tactiques propres (Tempo, Discipline de boost, Approche mécanique), chacun avec un vrai effet en match — mais seulement si votre effectif a le profil d'attributs pour le soutenir. Rôles dynamiques (1er/2e/3e homme), maîtrise de terrain et box-score réel (buts/passes/arrêts par joueur) sont désormais pris en compte pour TOUS les matchs de ligue, plus une préparation par adversaire, un ajustement automatique de tempo en cas de retard dans une série, et un bouton pour laisser le Head Coach gérer entièrement cette préparation tactique" },
    { key:'menu.patchnotes.item0j', fr:"Récap de match Valostrike (cartes simulées en 3D) refait pour refléter le vrai match joué : dégâts, HS%, KAST%, premiers kills/morts et clutchs sont désormais calculés à partir de ce qui s'est réellement passé sur la carte (le moteur 3D suit maintenant chaque dégât/tir/assist round par round) au lieu d'être estimés depuis les seuls attributs des joueurs — les assists, jusque-là toujours à 0, sont eux aussi vraiment comptabilisés" },
    { key:'menu.patchnotes.item0i', fr:"Correction d'un bug de stratégie Rocket Champ : un match RLCS (Opens/Majors/LCQ/Worlds) impliquant votre équipe ignorait totalement le style choisi dans « Formation & identité tactique » (et utilisait un calcul de force très simplifié) — aligné sur le même moteur que le reste de la ligue" },
    { key:'menu.patchnotes.item0h', fr:"Niveau de départ refait en 5 scénarios à identité propre (Streamer qui se lance, Repreneur d'un club, Startup ambitieuse, Structure sponsorisée, Personnalisé) au lieu de 4 paliers étoilés — chacun avec son propre équilibre budget/réputation/supporters (la Structure sponsorisée démarre avec un vrai sponsor déjà signé), le Personnalisé remplace le Mode Réaliste et laisse tout régler à la main via des curseurs" },
    { key:'menu.patchnotes.item0g', fr:"Nouveau système de blason : la Forge d'Identité (génération par mots-clés d'ambiance, 3 calques forme/emblème/accent réglables à la main, aperçu qui morphe en direct) remplace le badge texte-couleur, sur l'écran de création et partout où l'organisation s'affiche" },
    { key:'menu.patchnotes.item0f', fr:"Ratings Valostrike/Valostrike GC recalibrés sur l'échelle réelle de VLR.gg : une performance moyenne notait ~0.58 au lieu de ~1.00, toutes les notes du jeu paraissaient anormalement basses" },
    { key:'menu.patchnotes.item0e', fr:"Correction d'un bug de calendrier Valostrike GC : le Stage 3 (juillet-août) pouvait démarrer n'importe quand dans l'année sur une section rejointe après coup, provoquant des matchs hors saison (ex. en décembre)" },
    { key:'menu.patchnotes.item0d', fr:"Correction d'un bug critique du moteur 3D (cartes Zenith/Outpost) : « Passer le round » et « Simuler le match » ne faisaient plus avancer le temps de manche, qui tournait dans le vide sans jamais conclure" },
    { key:'menu.patchnotes.item0c', fr:"Score correctement centré dans le popup de match Rocket Champ en direct, quelle que soit la longueur des noms d'équipe" },
    { key:'menu.patchnotes.item0b', fr:"Écran de création : cases de sélection du jeu resserrées, alignées proprement en 2 par 2" },
    { key:'menu.patchnotes.item0a', fr:"Correction d'un bug de navigation : avancer d'un jour depuis une section ouverte via le sélecteur de la barre latérale ne vous renvoie plus dans une autre section" },
    { key:'menu.patchnotes.item1', fr:"Nouveau système de stratégie pour Rocket Champ : style d'équipe manuel (effet réel sur les matchs) et priorisation d'un attribut à l'entraînement" },
    { key:'menu.patchnotes.item2', fr:"Correction d'un bug d'affichage du sélecteur de section dans la barre latérale (menu tronqué/mal positionné)" },
    { key:'menu.patchnotes.item3', fr:"Ranked Valostrike rendu cohérent : le haut du ladder est maintenant dominé par de vrais pros signés en équipe VST International, plus par des agents libres au hasard" },
    { key:'menu.patchnotes.item4', fr:"Système de capitaine pour Rocket Champ : à désigner depuis la fiche d'un joueur, avec note de leadership et bonus d'équipe" },
    { key:'menu.patchnotes.item5', fr:"Mail : boîte de réception fusionnée entre toutes les sections actives, avec filtres par section, catégorie et priorité" },
    { key:'menu.patchnotes.item6', fr:"Lecteur de musique : barre d'avancement de la piste (avec temps écoulé/restant) et curseur de volume dédié, en plus du bouton muet" },
    { key:'menu.patchnotes.item7', fr:"Notes de mise à jour : la carte du menu principal ouvre désormais un popup avec le patch complet" },
    { key:'menu.patchnotes.item8', fr:"Suppression complète du système de logo/blason de l'organisation (création et affichage), remplacé par un badge de couleur avec le tag du club" },
  ] },
];

const CURRENT_PATCH_NOTES = PATCH_NOTES_HISTORY[0].notes;
const PATCHNOTES_WIDGET_PREVIEW_COUNT = 4;

function patchNotesEmptyLi(){
  return `<li class="mainmenu-patchnotes-empty">${T('menu.patchnotes.empty', 'Rien à signaler pour l\'instant sur cette version.')}</li>`;
}

function renderPatchnotesWidget(){
  const list = document.querySelector('.mainmenu-patchnotes-list');
  if(!list) return;
  list.innerHTML = CURRENT_PATCH_NOTES.length
    ? CURRENT_PATCH_NOTES.slice(0, PATCHNOTES_WIDGET_PREVIEW_COUNT).map(n => `<li>${T(n.key, n.fr)}</li>`).join('')
    : patchNotesEmptyLi();
  if (typeof applyI18n === 'function') applyI18n();
}

let patchNotesModalVersionIndex = 0;

function renderPatchNotesModalVersion(){
  const entry = PATCH_NOTES_HISTORY[patchNotesModalVersionIndex];
  const versionNode = document.getElementById('patchNotesModalVersion');
  const listNode = document.getElementById('patchNotesModalList');
  if (!entry || !versionNode || !listNode) return;

  versionNode.textContent = entry.version;
  listNode.innerHTML = entry.notes.length
    ? entry.notes.map(n => `<li>${T(n.key, n.fr)}</li>`).join('')
    : patchNotesEmptyLi();

  if (typeof applyI18n === 'function') applyI18n();

  const olderBtn = document.getElementById('patchNotesModalOlder');
  const newerBtn = document.getElementById('patchNotesModalNewer');
  if (olderBtn) olderBtn.disabled = patchNotesModalVersionIndex >= PATCH_NOTES_HISTORY.length - 1;
  if (newerBtn) newerBtn.disabled = patchNotesModalVersionIndex <= 0;
}

function openPatchNotesModal(){
  patchNotesModalVersionIndex = 0;
  renderPatchNotesModalVersion();
  const overlay = document.getElementById('patchNotesModalOverlay');
  if (overlay) overlay.style.display = 'flex';
}

function closePatchNotesModal(){
  const overlay = document.getElementById('patchNotesModalOverlay');
  if (overlay) overlay.style.display = 'none';
}
